<a href="https://colab.research.google.com/github/JakeOh/202103_itw_pyda_wkd/blob/main/da06_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*   **NumPy**: Numerical Python. 배열(array)들 빠르게 계산/조작할 수 있는 패키지(라이브러리)
*   **pandas**: Series, DataFrame을 다루는 패키지
*   **matplotlib**: 시각화(그래프) 패키지

In [1]:
import numpy as np

# Python list와 Numpy ndarray 비교

In [2]:
num_list = [1, 2, 3, 4, 5]
print(type(num_list))
print(num_list)

<class 'list'>
[1, 2, 3, 4, 5]


In [4]:
num_array = np.array([1, 2, 3, 4, 5])
print(type(num_array))
print(num_array)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [7]:
# numpy.ndarray도 list와 마찬가지로 아이템을 접근할 때 index를 사용
# slicing 기능은 list와 동일.
num_array[-2:]

array([4, 5])

In [8]:
# list에서 사용 가능한 연산자: + , *
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [12]:
# np.ndarray는 모든 산술 연산이 가능
# 산술 연산은 원소별(element-wise)로 이루어짐(같은 인덱스의 원소들끼리 연산)
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a1 + a2

array([5, 7, 9])

In [15]:
a1 * 2  # 배열 a1의 모든 원소에 같은 숫자 2를 곱해줌.(broadcast)

array([2, 4, 6])

In [17]:
# np.ndarray는 비교연산도 가능
np.array([1, -1, 2]) > 0

array([ True, False,  True])

# 2차원 array

In [22]:
a = np.arange(12).reshape((3, 4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [27]:
# 2차원 배열에서 index
print(a[0])  # 인덱스 0번 행(row)
print(a[0][1])  # 인덱스 0번 행의 인덱스 1번 아이템
print(a[0, 1])  # ndarray에서만 사용 가능.

[0 1 2 3]
1
1


# Indexing

*   list indexing(fancy indexing)

In [31]:
a = np.arange(10, 101, 10)
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


In [32]:
print(a[1:5])  # slicing

[20 30 40 50]


In [33]:
indexer = [1, 3, 5]
print(a[indexer])  # 인덱스들의 리스트(배열, 튜플)로 원소 선택

[20 40 60]


In [35]:
a[[3, 2, 1]]  # 인덱스의 순서를 원하는 대로

array([40, 30, 20])

*   boolean indexing

In [46]:
np.random.seed(1)
a = np.random.randint(-10, 10, size=10)
print(a)

[ -5   1   2  -2  -1   1  -5   5 -10   6]


In [47]:
a > 0  # bool(True/False)들의 배열

array([False,  True,  True, False, False,  True, False,  True, False,
        True])

In [48]:
a[a > 0]

array([1, 2, 1, 5, 6])

In [49]:
a[a % 2 == 0]

array([  2,  -2, -10,   6])

# Broadcast

In [50]:
a = np.arange(12).reshape((3, 4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [51]:
b = np.array([1, 1, 2, 2])
print(b)

[1 1 2 2]


In [52]:
print(a + b)

[[ 1  2  4  5]
 [ 5  6  8  9]
 [ 9 10 12 13]]


In [53]:
b = np.arange(1, 4).reshape((3, 1))
print(b)

[[1]
 [2]
 [3]]


In [54]:
print(a + b)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]


# numpy 함수, ndarray 메서드

numpy 패키지에서는 같은 기능이 함수와 메서드로 제공되는 경우가 많음.

In [55]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [56]:
np.sum(a)  # numpy 패키지가 가지고 있는 sum() 함수

10

In [57]:
a.sum()  # ndarray 클래스 객체인 a가 가지고 있는 sum() 메서드

10

In [58]:
type(a)

numpy.ndarray

*   np.mean(array): 평균. np.ndarray.mean()
*   np.var(): 분산(variance)
*   np.std(): 표준편차(standard deviation)
*   np.max(): 최댓값
*   np.min(): 최솟값

In [59]:
a = np.arange(12).reshape((3, 4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [60]:
np.sum(a)

66

In [61]:
a.sum()

66

In [62]:
np.sum(a, axis=0)

array([12, 15, 18, 21])

In [64]:
np.sum(a, axis=0, keepdims=True)

array([[12, 15, 18, 21]])

In [65]:
np.sum(a, axis=1, keepdims=True)

array([[ 6],
       [22],
       [38]])